### ISSUE TITLE
Remove oh-my-zsh dependency from powerlevel9k

### ISSUE THREAD

**Issue by dritter** [floriandejonckheere/PKGBUILD-AUR4#1]
Hi there!

Thank you very much, that you did an archlinux package for powerlevel9k. :+1: 

We put some effort to be framework agnostic, and like to keep it like that. Sadly, I saw that you coupled it quite tightly with oh-my-zsh. Is there any way to make this more flexible?

Like checking, if the user has installed oh-my-zsh or any other zsh framework?
Then the install script could link it in the appropriate folders? If no framework is installed, it could be sourced in `~/.zshrc` (or a similar configuration file).
But I must admit, that it might be error prone if the user installed the theme first, and installs a framework afterwards, the install script has to reconfigure the theme (like linking it to the right folder, so that the framework-theming-mechanism could work).

[These ](https://github.com/floriandejonckheere/PKGBUILD-AUR4/blob/f316adc3120267ed9ce4c85b283c663b09fa801f/oh-my-zsh-powerlevel9k-theme-git/PKGBUILD#L39-L44) are the lines that should be changed..

//cc @bhilburn

**Comment by floriandejonckheere** [comment]
Hi

I only started using zsh recently, so i don't really know my way around the different frameworks et cetera. I've made the package framework-agnostic, and added a link to the [installation instructions](https://github.com/bhilburn/powerlevel9k/wiki/Install-Instructions).

Oh-my-zsh users can create a simple symlink to use it:

```
ln -s /usr/share/zsh-theme-powerlevel9k /usr/share/oh-my-zsh/themes/powerlevel9k
```

Thanks for the suggestion.

Florian
